/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check endpoint */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Prometheus metrics endpoint */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Metrics in Prometheus format */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Public instance configuration
     * @description Unauthenticated. Tells clients which sign-up and login flows are enabled on this instance.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Instance configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["InstanceConfig"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/social/:provider": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Initiate social login with specified provider */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: "google" | "slack";
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to provider's login page */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/social/:provider/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Social login callback endpoint */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: "google" | "slack";
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful authentication */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Authentication failed */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sign-up": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Manual sign up endpoint */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description User's first name */
            first_name: string;
            /** @description User's last name */
            last_name: string;
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * Format: password
             * @description User's password (12-72 characters)
             */
            password: string;
            /** @description Name of the team (required unless team_invite_uuid is provided) */
            team_name?: string;
            /**
             * Format: uuid
             * @description UUID for team invitation (if joining an existing team)
             */
            team_invite_uuid?: string;
            /** @description Cloudflare Turnstile token. Required when Turnstile is enabled server-side; ignored otherwise. */
            turnstile_token?: string;
          };
        };
      };
      responses: {
        /** @description Successfully signed up */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description JWT authentication token */
              token?: string;
              user?: components["schemas"]["PrivateUser"];
            };
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User with this email already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sign-in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Manual sign in endpoint */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * Format: password
             * @description User's password
             */
            password: string;
            /** @description Cloudflare Turnstile token. Required when Turnstile is enabled server-side; ignored otherwise. */
            turnstile_token?: string;
          };
        };
      };
      responses: {
        /** @description Successfully signed in */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description JWT authentication token */
              token?: string;
            };
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Invalid email or password */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Too many sign-in attempts; retry after the window elapses */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request password reset email
     * @description Sends a password reset link to the specified email address if it exists in the system. Always returns success to avoid user enumeration.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description Cloudflare Turnstile token. Required when Turnstile is enabled server-side; ignored otherwise. */
            turnstile_token?: string;
          };
        };
      };
      responses: {
        /** @description Success message (always returned regardless of whether email exists) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example If the email you specified exists in our system, we've sent a password reset link to it. */
              message?: string;
            };
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reset-password/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Reset password using token
     * @description Resets the user's password using a valid password reset token
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Password reset token received via email */
          token: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: password
             * @description New password (12-72 characters; 72 is bcrypt's byte ceiling)
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description Password reset successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Your password has been changed. You can now use it to log in. */
              message?: string;
            };
          };
        };
        /** @description Invalid input, missing token, invalid/expired token, or token already used */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/auth/authenticate-app": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Create JWT token for desktop app */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successfully authenticated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              token?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user details */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User details retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PrivateUser"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/teammates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user's teammates */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of teammates retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BaseUser"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/websocket": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** WebSocket connection endpoint */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Switching protocols to WebSocket */
        101: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/update-user-name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update user's first and last name */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description User's first name */
            first_name: string;
            /** @description User's last name */
            last_name: string;
          };
        };
      };
      responses: {
        /** @description Name updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PrivateUser"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/team": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update the current admin's team
     * @description Updates the authenticated team admin's team. Currently only the team name can be changed. Used by onboarding to rename the placeholder team created at signup.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description New team name */
            name: string;
          };
        };
      };
      responses: {
        /** @description Team updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Team"];
          };
        };
        /** @description Invalid input or user is not part of any team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - user is not a team admin */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/auth/get-invite-uuid": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get or create a team invitation UUID
     * @description Returns a UUID that can be used to invite users to the team. If the existing invitation has expired, a new one is created.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Team invitation UUID retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /**
               * Format: uuid
               * @description UUID for team invitation
               */
              invite_uuid?: string;
              /** @description Name of the team */
              team_name?: string;
            };
          };
        };
        /** @description User is not part of any team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/send-team-invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send team invitation emails
     * @description Sends invitation emails to a list of email addresses to join the user's team
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description List of email addresses to invite */
            invitees: string[];
          };
        };
      };
      responses: {
        /** @description Invitations sent successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid request or user is not part of any team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/metadata/onboarding-form": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update onboarding form status */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @description Free-form onboarding survey answers */
            onboarding?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Onboarding form status updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invitation-details/{uuid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get team details for an invitation
     * @description Returns information about the team associated with an invitation UUID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uuid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Team details retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description Name of the team the user is invited to join */
              name?: string;
              /**
               * Format: uint
               * @description ID of the team the user is invited to join
               */
              team_id?: number;
            };
          };
        };
        /** @description Invalid invitation UUID */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Invitation not found or has expired */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/room": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new room */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description Name of the room */
            name?: string;
          };
        };
      };
      responses: {
        /** @description LiveKit tokens retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Room"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/rooms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all rooms for the user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Rooms for user retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Room"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/rooms/presence": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current participants in each room
     * @description Returns a map of room IDs to arrays of participant user IDs currently connected to each room
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Room presence data retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RoomsPresenceResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/calls/presence": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get call presence for user and teammates
     * @description Returns which users are currently in a 1:1 call or room call
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Call presence data retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CallsPresenceResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/call/join/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Join an ongoing call with a teammate
     * @description Join an existing 1:1 call that a teammate is currently in. Returns LiveKit tokens for the call room.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The user ID of the teammate whose call to join */
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description LiveKit tokens for the call */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SessionTokensResponse"];
          };
        };
        /** @description Trial or subscription expired */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example trial-ended */
              error?: string;
            };
          };
        };
        /** @description Target user is not a teammate */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Target user is not in a call */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Call ended while joining */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/room/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get LiveKit tokens for joining the team's selected room */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The ID of the room to retrieve */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description LiveKit tokens retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SessionTokensResponse"];
          };
        };
        /** @description Trial or subscription expired */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example trial-ended */
              error?: string;
            };
          };
        };
        /** @description User does not belong to the room's team */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Room not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": string;
          };
        };
      };
    };
    /** Update room details */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The ID of the room to update */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description Name of the room */
            name?: string;
          };
        };
      };
      responses: {
        /** @description Room updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Room"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    post?: never;
    /** Get LiveKit tokens for joining the team's selected room */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The ID of the room to delete */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User successfully deleted (no content) */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/livekit/server-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the LiveKit server url
     * @description Get the LiveKit server url
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description LiveKit server url */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description LiveKit server url */
              url?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit post-call feedback
     * @description Submit feedback after a call ends including rating and optional text feedback
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description ID of the team */
            team_id?: string;
            /** @description ID of the room where the call took place */
            room_id?: string;
            /** @description Rating score from 1 (worst) to 5 (best) */
            score: number;
            /** @description Optional text feedback */
            feedback?: string;
            /** @description Optional unstructured metadata */
            metadata?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Feedback submitted successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input (e.g., score out of range) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/change-team/{uuid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change user's team using invitation UUID
     * @description Allows a logged-in user to change teams using an invitation UUID. The user must have no teammates to perform this operation.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID of the team invitation */
          uuid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successfully changed team */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Successfully changed team */
              message?: string;
              /** @description Name of the new team */
              team_name?: string;
              /**
               * Format: uint
               * @description ID of the new team
               */
              team_id?: number;
            };
          };
        };
        /** @description User was already in this team - noop */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Invitation not found or has expired */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Cannot change teams - user has teammates */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/subscribe-linux-waitlist": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Subscribe to Linux waiting list
     * @description Subscribes the authenticated user to the Linux waiting list and unsubscribes from marketing emails
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successfully subscribed to Linux waiting list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example Successfully subscribed to Linux waiting list */
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/teammates/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove a teammate from your team
     * @description Removes a user from the team and automatically creates a new solo team for them. The removed user becomes an admin of their new team and can continue using Hopp. Admins cannot remove themselves.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description UUID of the user to remove from the team */
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Teammate removed successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad request - missing userId, cannot remove yourself, or cannot remove last admin */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - user is not an admin or target user is not in your team */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/billing/subscription": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current subscription status
     * @description Returns the subscription status for the current user's team
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Subscription status retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              subscription?: components["schemas"]["SubscriptionResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/billing/create-checkout-session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Stripe checkout session
     * @description Creates a Stripe checkout session for team subscription
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
        };
      };
      responses: {
        /** @description Checkout session created successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description URL to redirect user to Stripe checkout */
              checkout_url: string;
              /** @description Stripe checkout session ID */
              session_id: string;
            };
          };
        };
        /** @description Bad request - invalid input or team already has active subscription */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - only team admins can manage subscriptions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/billing/create-portal-session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Stripe billing portal session
     * @description Creates a Stripe billing portal session for subscription management
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Portal session created successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description URL to redirect user to Stripe billing portal */
              portal_url: string;
            };
          };
        };
        /** @description Bad request - user must be part of a team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - only team admins can access billing portal */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description No subscription found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/billing/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get billing settings
     * @description Returns the billing settings for the current user's team, including the billing email where invoices are sent
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Billing settings retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BillingSettingsResponse"];
          };
        };
        /** @description Bad request - user must be part of a team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - only team admins can view billing settings */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /**
     * Update billing settings
     * @description Updates the billing settings for the current user's team. Set billing_email to configure where invoices are sent, or leave empty to disable invoice emails.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BillingSettingsRequest"];
        };
      };
      responses: {
        /** @description Billing settings updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BillingSettingsResponse"];
          };
        };
        /** @description Bad request - invalid email format or user must be part of a team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - only team admins can update billing settings */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slack/join/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Join a Slack pairing session
     * @description Validates the room exists and redirects to the web-app's /slack/join/:sessionId
     *     route, which handles authentication and deep-links to the desktop app.
     *     This endpoint is called when users click "Join" on a Slack call card.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The session/room ID to join */
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to web-app's Slack join page */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Session not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/slack/session/{sessionId}/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get LiveKit tokens for a Slack session
     * @description Returns LiveKit tokens for joining a Slack room. Called by the desktop app
     *     when handling a join-session deep-link. For Slack rooms, this also adds
     *     the user as a participant to the Slack call.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The session/room ID to get tokens for */
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description LiveKit tokens generated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SessionTokensResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Session not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/slack/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Initiate Slack app installation
     * @description Initiates the Slack OAuth flow to install the Hopp app in a Slack workspace.
     *     This is an authenticated endpoint - the user's identity is stored and linked
     *     to the installation on callback. Accepts token via Authorization header or
     *     query parameter (for browser redirects).
     */
    get: {
      parameters: {
        query?: {
          /** @description JWT token (alternative to Authorization header for browser redirects) */
          token?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirects to Slack OAuth authorization URL */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User is not part of a team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Slack app not configured */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/slack/installation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Slack installation for user's team
     * @description Returns the Slack installation linked to the current user's team.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Slack installation retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SlackInstallation"];
          };
        };
        /** @description User is not part of a team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description No Slack installation found for this team */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete Slack installation for user's team
     * @description Deletes the Slack installation linked to the current user's team.
     *     Only team admins can delete the installation.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Slack installation deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User is not part of a team */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden - only admins can delete Slack installations */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description No Slack installation found for this team */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/room/{id}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Leave a room
     * @description Called when a user leaves a room. For Slack rooms, this removes the user
     *     from the Slack call and updates the room's LastParticipantLeftAt timestamp.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The room ID to leave */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successfully left the room */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Room not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BaseUser: {
      /** Format: uuid */
      readonly id: string;
      first_name: string;
      last_name: string;
      /** Format: email */
      email: string;
      team_name: string;
      avatar_url?: string | null;
      /** @default false */
      is_admin: boolean;
      /** @description Whether the user is currently active (connected via websocket) */
      is_active?: boolean;
      /** Format: uint */
      team_id?: number;
      /** Format: date-time */
      readonly created_at?: string;
      /** Format: date-time */
      readonly updated_at?: string;
    };
    PrivateUser: components["schemas"]["BaseUser"] & {
      social_metadata?: {
        [key: string]: unknown;
      } | null;
      metadata?: {
        [key: string]: unknown;
      } | null;
      /** @description Whether the user has an active paid subscription */
      is_pro?: boolean;
      /** @description Whether the user is currently in trial period */
      is_trial?: boolean;
      /**
       * Format: date-time
       * @description When the trial period ends (null if not in trial or has active subscription)
       */
      trial_ends_at?: string | null;
    };
    Team: {
      /** Format: uint */
      readonly ID: number;
      name: string;
      is_manual_upgrade?: boolean;
      billing_email?: string | null;
      /** Format: date-time */
      readonly CreatedAt?: string;
      /** Format: date-time */
      readonly UpdatedAt?: string;
    };
    Room: {
      /** Format: uuid */
      id: string;
      name: string;
      user_id: string;
    };
    RoomsPresenceResponse: {
      /** @description Map of room IDs to arrays of participant user IDs */
      rooms: {
        [key: string]: string[];
      };
    };
    CallPresence: {
      /** @description Peer user IDs in the call */
      peerIds?: string[];
      /** @description Room name (for room calls) */
      roomName?: string;
    };
    CallsPresenceResponse: {
      /** @description Map of user IDs to their call presence state */
      presence: {
        [key: string]: components["schemas"]["CallPresence"];
      };
    };
    Error: {
      message?: string;
    };
    SubscriptionResponse: {
      /**
       * @description Current subscription status
       * @enum {string}
       */
      status: "active" | "canceled" | "past_due" | "trialing" | "incomplete";
      /** @description Whether the team has been manually upgraded */
      manual_upgrade: boolean;
      /**
       * @description Billing interval for the subscription (omitted for manual upgrades or trialing)
       * @enum {string}
       */
      billing_interval?: "monthly" | "yearly";
      /**
       * Format: date-time
       * @description End date of current billing period (null for manual upgrades or trialing)
       */
      current_period_end?: string | null;
      /** @description Whether subscription will cancel at period end (null for manual upgrades or trialing) */
      cancel_at_period_end?: boolean | null;
      /** @description Whether the current user is a team admin */
      is_admin: boolean;
      /** @description Whether the team must add a payment method to access the product (post-cutoff team with no active/trialing subscription). Drives the blocking onboarding/paywall gate for admins. */
      requires_payment_method: boolean;
      /** @description Whether a real Stripe subscription row exists for the team, i.e. the billing portal can be opened. False for legacy (pre-cutoff) trial teams and manual-upgrade teams, which have no Stripe subscription to manage. */
      has_stripe_subscription: boolean;
    };
    CreateCheckoutSessionRequest: {
      /**
       * @description Subscription tier to create checkout session for
       * @enum {string}
       */
      tier: "paid";
      /**
       * @description Billing interval (defaults to monthly if omitted)
       * @enum {string}
       */
      interval?: "monthly" | "yearly";
      /** @description Optional Stripe price ID (uses environment default if not provided) */
      price_id?: string;
    };
    BillingSettingsRequest: {
      /**
       * Format: email
       * @description Email address where invoices will be sent (leave empty to disable invoice emails)
       */
      billing_email?: string;
    };
    BillingSettingsResponse: {
      /** @description Email address where invoices are sent (empty string if not configured) */
      billing_email: string;
    };
    SessionTokensResponse: {
      /** @description LiveKit token for audio track */
      audioToken: string;
      /** @description LiveKit token for screenshare video track */
      videoToken: string;
      /** @description LiveKit token for camera video track */
      cameraToken: string;
      /** @description Participant identity for the session */
      participant: string;
      /** @description Included when the session is a named room (not an ad-hoc call) */
      room?: components["schemas"]["Room"];
    };
    SlackInstallation: {
      /** @description Installation ID */
      id: number;
      /** @description Slack workspace/team ID */
      slack_team_id: string;
      /** @description Slack workspace/team name */
      slack_team_name: string;
      /** @description Slack bot user ID */
      bot_user_id?: string;
      /** @description OAuth scopes granted to the bot */
      scopes?: string;
      /**
       * Format: date-time
       * @description When the app was installed
       */
      installed_at?: string;
      /** @description Hopp user ID who installed the app */
      installed_by_id?: string;
      /** @description Hopp team ID linked to this installation */
      team_id?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    /** @description Public configuration of this instance, used by clients to hide flows the backend would reject */
    InstanceConfig: {
      /** @description False when DISABLE_SIGNUP is set and the instance already has users; new accounts then need a team invitation */
      signup_enabled: boolean;
      /** @description False when DISABLE_PASSWORD_LOGIN is set; only social providers can be used */
      password_login_enabled: boolean;
      /** @description True when Stripe billing is configured */
      billing_enabled: boolean;
      /** @description Social login providers that are configured on this instance */
      auth_providers: ("google" | "slack" | "github")[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
